### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [uzh/gc3pie#264]
```
Python 3 is now getting mainstream so it's time to think of a Python3
port of GC3Pie.  However, with the release schedule of CentOS/RHEL and
Debian (stable), we should continue to support Python2 for a few years
to come.

This is a web page that lists tricks and strategies to produce code
that is compatible with both Py2 and Py3:

    http://python3porting.com/noconv.html

This ticket is meant to be a meta-ticket that depends on the specific
issues in converting the source files.

```

Original issue reported on code.google.com by `riccardo.murri@gmail.com` on 8 May 2012 at 8:53

**Comment by Unode** [comment]
Any progress on this?
I see from `.travis.yml` that python3 is still not a test target.
The last comment on this issue is also from over a year ago.

**Comment by alpae** [comment]
Hi, any further progress on this issue? paramico for example is by now py3 compatible. would be nice to see any progress towards py3 compatibility.

**Comment by riccardomurri** [comment]
hello!

You're right -- this is way overdue... Do you have any deadlines or scheduled releases that would require GC3Pie to be Py3-compatible>

Unfortunately, I cannot commit to any date/release for Py3 support ATM. But I'd be more than happy to help if anyone wants to start working on it and make a PR.

**Comment by alpae** [comment]
I'm new to gc3pie - actually never used it myself, but highly interested. Most of my projects are nowadays in py3, so it would be quite important to me. I would be happy to help out with making the code py3 compatible. I'm often in Zurich, so if we could meet at some point to have a brief discussion how to go about this, that would be helpful to get me started. Also, just to get an idea of what has already been tried out and where the biggest issues will probably lie.

**Comment by riccardomurri** [comment]
hi @alpae - sorry for the late reply!

I would be happy to meet and discuss when you're in Zurich and have time! Just send me an email or reach out on the [GC3Pie chat room][1].

As far as the porting is concerned, I see two main issues:

- iteration over dictionaries: GC3Pie code uses quite liberally `.keys()` and `.items()` some times just to iterate (-> could be replaced with `.iterkeys()` or `.itervalues()`), some times to iterate *over a copy* (-> need to be explicit in Py3 AFAICT)
- Python3 defaulting to UTF-8 encoding for file names.  This is not much an issue in the code but just assuming that every file name is UTF-8 encoded/decodable will break some users' habits. So, ideally GC3Pie should treat file names as byte strings -- but AFAICT that's not the default in Py3 and needs some additional care.

[1]: https://gitter.im/gc3pie/chat

**Comment by versae** [comment]
Any update on this?

**Comment by riccardomurri** [comment]
I have created a branch https://github.com/riccardomurri/gc3pie/tree/python3 to address the porting issues; not much in there but at least Travis will pester me with failed test notifications until Py3 porting has been completed...

**Comment by boegel** [comment]
While working on porting EasyBuild to Python 3, I noticed that GC3Pie doesn't support Python 3 yet, and then I found this issue.

Any updates on this? Is anything in particular blocking you from making progress towards (also) supporting Python 3? Is there an ETA for Python 3 support in GC3Pie?

**Comment by riccardomurri** [comment]
@boegel Let me turn the question around :-) When do you plan to release EB with Py3 support? We'll try to meet that deadline...

**Comment by boegel** [comment]
@riccardomurri We've started actively working on support EasyBuild on top of Python 3 in a separate `4.x` branch (see https://github.com/easybuilders/easybuild-framework/labels/python3), where the goal is to have full Python 3 support in EasyBuild 4.0 (https://github.com/easybuilders/easybuild/issues/447).

There's no hard deadline, it'll be ready whenever it's ready, but I hope to get EasyBuild 4.0 released by summer 2019 (maybe even sooner).

**Comment by riccardomurri** [comment]
Good news everyone: @malmstroem will start working on this soon ;-)

**Comment by riccardomurri** [comment]
Quick summary of a discussion held this morning with @malmstroem.

We agreed that it would be better to do the porting in steps:

1. Run [`pylint --py3k`][1] on all source files, to ensure code is
   forward-compatible (or at least get an idea of potential
   incompatibilities).
2. Insert `from __future__ import ...` lines in all source modules and
   run extensive tests, to ensure GC3Pie doesn't break if we start
   using, e.g., byte strings for file names)
3. Use [futurize][2] to actually update the code.

[1]: https://portingguide.readthedocs.io/en/latest/tools.html#automated-checker-pylint-py3k
[2]: https://python-future.org/futurize.html

**Comment by riccardomurri** [comment]
Questions still open:

* Can we have a non-critical test suite on Travis CI that tells us "how far" we are from a Py3 codebase? e.g. no errors in `pylint --py3k` but without failing the test suite?
* Is it better to keep file names as Python `str` strings or use `bytes` strings instead? See: http://changelog.complete.org/archives/9938-the-python-unicode-mess

**Comment by boegel** [comment]
Travis has support for allowed failures, see https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail

**Comment by riccardomurri** [comment]
As for step 2. above, according to the [documentation of the
`__future__` module in Python 2.7][1], we should have this line to
enable the maximum Py3 compatibility:

       from __future__ import (division, absolute_import, print_function, unicode_literals)

[1]: https://docs.python.org/2/library/__future__.html

**Comment by riccardomurri** [comment]
@malmstroem Travis CI is now testing GC3Pie on Python 3 (thx @boegel for the tip on allowed failures), but they don't count towards the build pass/fail status.  See for example: https://travis-ci.org/uzh/gc3pie/jobs/486839442 (which BTW highlights that `inotifyx` is not compatible with Python 3... :-/ )

I have also added coverage reports in the tests (but they only run if all tests were successful).

**Comment by riccardomurri** [comment]
I've made PR #654 with my code patches so far.

**Comment by riccardomurri** [comment]
Quick update for those who are not following PR #654 : the code in that branch now passes all tests in Py2 after code modernization (which hopefully makes it Py3 compliant).

**Comment by riccardomurri** [comment]
We're now at the point were the modernized code passes all tests on Py2.7 (fails some on Py2.6, anybody volunterring for checking exactly why?), is *mostly* OK on Py3.5+ **but** now tests in Py3 start to fail because of the unwanted mixing of unicode strings and byte strings in the backend code, e.g., things like this:

```python
Traceback (most recent call last):
  File "/home/rmurri/w/gc3pie/gc3libs/core.py", line 367, in __submit_application
    resource.submit_job(app)
  File "/home/rmurri/w/gc3pie/gc3libs/backends/__init__.py", line 166, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/rmurri/w/gc3pie/gc3libs/backends/batch.py", line 420, in submit_job
    ssh_remote_folder = stdout.split('\n')[0]
TypeError: a bytes-like object is required, not 'str'
```

All stdout and stderr collected from subprocesses is a byte string, temporary files as returned by `tempfile` are opened for binary r/w, which means that probably all backend code should be doing binary I/O but other parts of the stdlib return unicode strings (e.g., `os.listdir()` or `os.environ`) so the exact boundary where we should be having the conversion is not clear...

**Comment by interrogator** [comment]
Nice to see the progress! Great job.

bytes/str might be a bit tough. First off I think `compat` should have two different file openers and import the right one based on Python version. Python 2 probably has to use `codecs.open`. I can make a PR with this, let me know if you can think of other converters and I can add them also.

**Comment by riccardomurri** [comment]
With the latest commits in #654 , all tests pass on Python 2.7, 3.5, 3.6, and 3.7.

@boegel @malmstroem @ehrenfeu Would you have some time to check out the code in PR #654 and see if it breaks your codes?

**Comment by ehrenfeu** [comment]
Hi Riccardo, that's great news!

I'm more than happy to do some tests once I can contribute some time to my gc3pie project again, hopefully in the next few weeks.

Thanks for your work on this!

**Comment by boegel** [comment]
@riccardomurri Gave it a quick test using your `python3` branch (commit 0d60f89) using Python 2(.7.5) and EasyBuild develop (basically v3.9.3 with some sugar on top), ran into this issue:

```
$ export EASYBUILD_JOB_BACKEND_CONFIG=$PWD/gc3pie.cfg
$ cat $EASYBUILD_JOB_BACKEND_CONFIG
[resource/localhost]
enabled = yes
type = shellcmd
frontend = localhost
transport = local
max_memory_per_core = 10GiB
max_walltime = 100 hours
# max # jobs ~= max_cores / max_cores_per_job
max_cores_per_job = 1
max_cores = 4
architecture = x86_64
auth = none
override = no
resourcedir = /tmp/gc3pie
```

```
$ eb CMake-3.13.3-GCCcore-8.2.0.eb zlib-1.2.11-GCCcore-8.2.0.eb -df --job --job-backend=GC3Pie --job-cores 4 --job-max-walltime 3
== temporary log file in case of crash /tmp/eb-tp3xLz/easybuild-7Jk4t6.log
  >> sources:
  >> /sources/c/CMake/cmake-3.13.3.tar.gz
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/foo/lib/python2.6/site-packages/easybuild_framework-3.9.4.dev0-py2.7.egg/easybuild/main.py", line 457, in <module>
    main()
  File "/foo/lib/python2.6/site-packages/easybuild_framework-3.9.4.dev0-py2.7.egg/easybuild/main.py", line 415, in main
    submit_jobs(ordered_ecs, eb_go.generate_cmd_line(), testing=testing)
  File "/foo/lib/python2.6/site-packages/easybuild_framework-3.9.4.dev0-py2.7.egg/easybuild/tools/parallelbuild.py", line 144, in submit_jobs
    return build_easyconfigs_in_parallel(command, ordered_ecs, prepare_first=prepare_first)
  File "/foo/lib/python2.6/site-packages/easybuild_framework-3.9.4.dev0-py2.7.egg/easybuild/tools/parallelbuild.py", line 107, in build_easyconfigs_in_parallel
    active_job_backend.queue(new_job, job_deps)
  File "/foo/lib/python2.6/site-packages/easybuild_framework-3.9.4.dev0-py2.7.egg/easybuild/tools/job/gc3pie.py", line 210, in queue
    self.jobs.add(job, dependencies)
  File "build/bdist.linux-x86_64/egg/gc3libs/workflow.py", line 1242, in add
TypeError: unhashable type: 'Application'
```

This may be something we deal with on our end though, not sure, need to take a closer look.

**Comment by riccardomurri** [comment]
@boegel I think I've fixed that in 17580f18 -- can you please retest?

**Comment by boegel** [comment]
Same problem occurred when using a pre-release of EasyBuild 4.0 on top of Python 3.

I've retested with 56d018 on top of Python 3 just now, the `TypeError: unhashable type: 'Application'` is resolved, but now I'm seeing something else:

```
== GC3Pie job overview: 2 new (total: 2)
== GC3Pie job overview: 2 submitted (total: 2)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/software/EasyBuild/4.0.0.dev0-on-par-with-eb393/lib/python2.7/site-packages/easybuild_framework-4.0.0.dev0-py2.7.egg/easybuild/main.py", line 462, in <module>
    main()
  File "/software/EasyBuild/4.0.0.dev0-on-par-with-eb393/lib/python2.7/site-packages/easybuild_framework-4.0.0.dev0-py2.7.egg/easybuild/main.py", line 420, in main
    submit_jobs(ordered_ecs, eb_go.generate_cmd_line(), testing=testing)
  File "/software/EasyBuild/4.0.0.dev0-on-par-with-eb393/lib/python2.7/site-packages/easybuild_framework-4.0.0.dev0-py2.7.egg/easybuild/tools/parallelbuild.py", line 144, in submit_jobs
    return build_easyconfigs_in_parallel(command, ordered_ecs, prepare_first=prepare_first)
  File "/software/EasyBuild/4.0.0.dev0-on-par-with-eb393/lib/python2.7/site-packages/easybuild_framework-4.0.0.dev0-py2.7.egg/easybuild/tools/parallelbuild.py", line 114, in build_easyconfigs_in_parallel
    active_job_backend.complete()
  File "/software/EasyBuild/4.0.0.dev0-on-par-with-eb393/lib/python2.7/site-packages/easybuild_framework-4.0.0.dev0-py2.7.egg/easybuild/tools/job/gc3pie.py", line 254, in complete
    self._engine.progress()
  File "/software/GC3Pie/python3-py3/lib/python3.6/site-packages/gc3pie-2.5.3-py3.6.egg/gc3libs/core.py", line 1742, in progress
  File "/software/GC3Pie/python3-py3/lib/python3.6/site-packages/gc3pie-2.5.3-py3.6.egg/gc3libs/core.py", line 1719, in progress
  File "/software/GC3Pie/python3-py3/lib/python3.6/site-packages/gc3pie-2.5.3-py3.6.egg/gc3libs/core.py", line 430, in update_job_state
  File "/software/GC3Pie/python3-py3/lib/python3.6/site-packages/gc3pie-2.5.3-py3.6.egg/gc3libs/core.py", line 468, in __update_application
  File "/software/GC3Pie/python3-py3/lib/python3.6/site-packages/gc3pie-2.5.3-py3.6.egg/gc3libs/core.py", line 458, in __update_application
  File "/software/GC3Pie/python3-py3/lib/python3.6/site-packages/gc3pie-2.5.3-py3.6.egg/gc3libs/backends/__init__.py", line 168, in wrapper
  File "/software/GC3Pie/python3-py3/lib/python3.6/site-packages/gc3pie-2.5.3-py3.6.egg/gc3libs/backends/batch.py", line 579, in update_job_state
  File "/software/GC3Pie/python3-py3/lib/python3.6/site-packages/gc3pie-2.5.3-py3.6.egg/gc3libs/backends/batch.py", line 554, in __run_command_and_parse_output
  File "/software/GC3Pie/python3-py3/lib/python3.6/site-packages/gc3pie-2.5.3-py3.6.egg/gc3libs/backends/slurm.py", line 203, in _parse_stat_output
ValueError: not enough values to unpack (expected 3, got 1)
```

Jobs are being submitted, but they're not working as expected (that could be related to the setup I'm testing with though, since I'm submitting from Python 3 but the `eb` in the jobs will be Python 2).

**Comment by boegel** [comment]
Similar error but in a different part of the code when using Python 2:

```
== GC3Pie job overview: 2 new (total: 2)
== GC3Pie job overview: 2 submitted (total: 2)
== GC3Pie job overview: 2 running (total: 2)
== GC3Pie job overview: 2 running (total: 2)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/software/EasyBuild/3.9.3/lib/python2.7/site-packages/easybuild_framework-3.9.3-py2.7.egg/easybuild/main.py", line 457, in <module>
    main()
  File "/software/EasyBuild/3.9.3/lib/python2.7/site-packages/easybuild_framework-3.9.3-py2.7.egg/easybuild/main.py", line 415, in main
    submit_jobs(ordered_ecs, eb_go.generate_cmd_line(), testing=testing)
  File "/software/EasyBuild/3.9.3/lib/python2.7/site-packages/easybuild_framework-3.9.3-py2.7.egg/easybuild/tools/parallelbuild.py", line 144, in submit_jobs
    return build_easyconfigs_in_parallel(command, ordered_ecs, prepare_first=prepare_first)
  File "/software/EasyBuild/3.9.3/lib/python2.7/site-packages/easybuild_framework-3.9.3-py2.7.egg/easybuild/tools/parallelbuild.py", line 114, in build_easyconfigs_in_parallel
    active_job_backend.complete()
  File "/software/EasyBuild/3.9.3/lib/python2.7/site-packages/easybuild_framework-3.9.3-py2.7.egg/easybuild/tools/job/gc3pie.py", line 251, in complete
    self._engine.progress()
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 1742, in progress
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 1719, in progress
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 430, in update_job_state
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 468, in __update_application
ValueError: need more than 1 value to unpack
```

**Comment by riccardomurri** [comment]
Should be fixed in 2a6aab0b (latest commit on this branch), can you please try again?

**Comment by boegel** [comment]
@riccardomurri Working like a charm now, both with Python 2 and 3 :+1:

```
$ eb libreadline-8.0.eb ncurses-6.1.eb --robot -df --job --job-backend=GC3Pie --job-cores 2 --job-max-walltime 1  --job-backend-config=$PWD/gc3pie-slurm.cfg
== temporary log file in case of crash /tmp/eb-K6INXq/easybuild-8xcTI7.log

== resolving dependencies ...

== GC3Pie job overview: 1 new (total: 2)
== GC3Pie job overview: 1 submitted (total: 2)
== GC3Pie job overview: 1 running (total: 2)
...
== GC3Pie job overview: 1 running (total: 2)
== GC3Pie job overview: 1 terminated, 1 ok (total: 2)
== GC3Pie job overview: 1 terminated, 1 ok, 1 submitted (total: 2)
== GC3Pie job overview: 1 terminated, 1 ok, 1 running (total: 2)
== GC3Pie job overview: 1 terminated, 1 ok, 1 running (total: 2)
== GC3Pie job overview: 1 terminated, 1 ok, 1 running (total: 2)
== GC3Pie job overview: 2 terminated, 2 ok (total: 2)
== GC3Pie job overview: 2 terminated, 2 ok (total: 2)
== Done processing jobs
== GC3Pie job overview: 2 terminated, 2 ok (total: 2)
== Submitted parallel build jobs, exiting now
== Temporary log file(s) /tmp/eb-K6INXq/easybuild-8xcTI7.log* have been removed.
== Temporary directory /tmp/eb-K6INXq has been removed.
```

**Comment by riccardomurri** [comment]
Python3 support was just merged into "master".

Thanks everyone for testing this out and contributing to the port!
