### ISSUE TITLE
early errors in VM creation lead to `KeyError` when submitting job

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#505]
When submitting jobs to the OpenStack backend, due to some server-side
misconfiguration the VMs turn immediately into ERROR state.  However,
GC3Pie does not handle the situation gracefully::

        gc3.gc3libs: INFO: VM with id `f7c9a19b-045f-4c9e-939c-26f7eb9aba57` has been created and is in BUILD state.
        gc3.gc3libs: DEBUG: No available resource was found, but some VM is still in `pending` state. Waiting until the next iteration before creating a new VM. Pending VM ids: set([u'f7c9a19b-045f-4c9e-939c-26f7eb9aba57'])
        gc3.gc3libs: INFO: Submission of job FunctionalDiversityApplication.14 delayed
        gc3.gc3libs: ERROR: Got error in submitting task 'FunctionalDiversityApplication.14', informing scheduler: LRMSSkipSubmissionToNextIteration: Delaying submission until some of the VMs currently pending is ready. Pending VM ids: f7c9a19b-045f-4c9e-939c-26f7eb9aba57
        gc3.gc3libs: DEBUG: Performing matching of resource(s) sciencecloud to task 'FunctionalDiversityApplication.15' ...
        gc3.gc3libs: DEBUG: Checking resource 'sciencecloud' for compatibility with application requirements
        gc3.gc3libs: DEBUG: Task compatiblity check returned 1 matching resources
        gc3.gc3libs: DEBUG: Submitting FunctionalDiversityApplication.15 ...
        gc3.gc3libs: DEBUG: Attempting submission to resource 'sciencecloud'...
        gc3.gc3libs: ERROR: VM with id `f7c9a19b-045f-4c9e-939c-26f7eb9aba57` is in ERROR state. Terminating it!
        gc3.gc3libs: INFO: Error in submitting job to resource 'sciencecloud': KeyError: u'f7c9a19b-045f-4c9e-939c-26f7eb9aba57'
        Traceback (most recent call last):
          File "/home/ubuntu/gc3pie/src/gc3libs/core.py", line 354, in __submit_application
            resource.submit_job(app)
          File "/home/ubuntu/gc3pie/src/gc3libs/backends/openstack.py", line 827, in submit_job
            self.get_resource_status()
          File "/home/ubuntu/gc3pie/src/gc3libs/backends/openstack.py", line 643, in get_resource_status
            self.subresources.pop(vm.id)
        KeyError: u'f7c9a19b-045f-4c9e-939c-26f7eb9aba57'

**Comment by riccardomurri** [comment]
Same error happens when quitting::

        ^Cgfdiv: Exiting upon user request (Ctrl+C)
        gc3.gc3libs: INFO: Closing connection to cloud 'sciencecloud'...
        gc3.gc3libs: ERROR: VM with id `607f0b81-633b-452e-aa44-7639123018a2` is in ERROR state. Terminating it!
        gc3.gc3utils: CRITICAL: KeyError: u'607f0b81-633b-452e-aa44-7639123018a2'
