### ISSUE TITLE
erratic behaviour of the 'security_group_name' option 

### ISSUE THREAD

**Issue by taleksiev** [uzh/gc3pie#511]
Documentation says: 'If a security group with the name is not found, a new one will be created.' 
When trying to do this I got the security group created but the session won't recognize it and will try to create a new one until the quota is exceeded.

**Comment by riccardomurri** [comment]
Confirmed. Apparently the bug is triggered only when the security
group name is not ``default`` -- quite likely because ``default`` already
exists and has the rules that GC3Pie needs (at least in UZH's Science Cloud).

Example traceback occurring during security group management::

    gmbsim: [2016-04-08 20:07:16] INFO    : Error in submitting job to resource 'sciencecloud': NotFound: Not found (HTTP Security group gc3pie not found.)
    Traceback (most recent call last):
      File "/home/gc3-user/gc3pie/src/gc3libs/core.py", line 354, in __submit_application
        resource.submit_job(app)
      File "/home/gc3-user/gc3pie/src/gc3libs/backends/openstack.py", line 894, in submit_job
        user_data=user_data)
      File "/home/gc3-user/gc3pie/src/gc3libs/backends/openstack.py", line 253, in _create_instance
        self._setup_security_groups()
      File "/home/gc3-user/gc3pie/src/gc3libs/backends/openstack.py", line 504, in _setup_security_groups
        self._get_security_group(self.security_group_name)
      File "/home/gc3-user/gc3pie/src/gc3libs/utils.py", line 204, in wrapper
        obj._cache_value[key] = fn(obj, *args)
      File "/home/gc3-user/gc3pie/src/gc3libs/backends/openstack.py", line 440, in _get_security_group
        raise NotFound("Security group %s not found." % name)
    NotFound: Not found (HTTP Security group gc3pie not found.)

Despite what the traceback/OpenStack API says, the security group *is*
created (can be seen from the web interface or the command-line
client).
