### ISSUE TITLE
OpenStack backend assumes `Application.requested_memory` is not `None`

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#559]
Despite the `requested_memory` (and all other `requested_*`
attributes) being *optional*, the OpenStack backend and -possibly- the
EC2 as well assume `job.requested_memory` is not set to `None` during
the search for a suitable flavor::

    ex2c.py: [2016-07-11 22:44:57] INFO    : Error in submitting job to resource 'sciencecloud': AssertionError: Cannot compare 'Memory' with 'NoneType': Can only compare homogeneous quantities!
    Traceback (most recent call last):
      File "/home/rmurri/gc3/gc3pie/gc3libs/core.py", line 354, in __submit_application
        resource.submit_job(app)
      File "/home/rmurri/gc3/gc3pie/gc3libs/backends/openstack.py", line 837, in submit_job
        instance_type = self.get_instance_type_for_job(job)
      File "/home/rmurri/gc3/gc3pie/gc3libs/backends/openstack.py", line 572, in get_instance_type_for_job
        >= job.requested_memory]
      File "/home/rmurri/gc3/gc3pie/gc3libs/quantity.py", line 130, in cmp_fn
        % (self.__class__.__name__, other.__class__.__name__))
    AssertionError: Cannot compare 'Memory' with 'NoneType': Can only compare homogeneous quantities!

This should be fixed and GC3Pie should use the configured flavor if
requirements are not specified.

(Thanks to Alexander Nater and Marc W. Schmid for reporting.)

**Comment by riccardomurri** [comment]
I think this is fixed in commit c4fdcc7b109cf128abacdcf9416ec85769362b38, where the internal logic of `OpenStackLrms.get_instance_type_for_job()` was rewritten.
