### ISSUE TITLE
Inconsistency in OpenStack's handling "instance_type" configuration items

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#564]
There is an inconsistency in the way the generic `instance_type` and
the application-specific one are handled in the OpenStack backend
(lines 556--578, function `get_instance_type_for_job`):

* If the application-specific `*_instance_type` configuration is
  provided, that setting is used right and an error is raised if it's
  incorrect.

* However, if no application-specific "instance type" is configured,
  then the generic setting is *ignored* and GC3Pie attempts
  auto-selecting the flavor based on the application requirements...

We should instead have the generic instance type act as a *minimum*:
auto-discovery should only be attempted if the application
requirements cannot be satisfied by it.

(Thanks to Alexander Nater for noticing.)

**Comment by riccardomurri** [comment]
Got this error report from Susanne::

    gc3.gc3libs: INFO: Biggest flavor available on the cloud: 32cpu-128ram-hpc
    gc3.gc3libs: INFO: Error in submitting job to resource 'sciencecloud': KeyError: 'gsphenotypicalhomologyexample_instance_type'
    Traceback (most recent call last):
      File "/home/sschindl/gc3pie/src/gc3libs/core.py", line 354, in __submit_application
        resource.submit_job(app)
      File "/home/sschindl/gc3pie/src/gc3libs/backends/openstack.py", line 872, in submit_job
        instance_type = self.get_instance_type_for_job(job)
      File "/home/sschindl/gc3pie/src/gc3libs/backends/openstack.py", line 592, in get_instance_type_for_job
        flavor_name = self[conf_option]
      File "/home/sschindl/gc3pie/src/gc3libs/utils.py", line 1534, in __getitem__
        return self.__dict__[name]
    KeyError: 'gsphenotypicalhomologyexample_instance_type'

It might be that the fix in commit 19a7ae9 contains some trivial error,
e.g. not checking for the existence of a dictionary key before referencing it.
