### ISSUE TITLE
GC3Pie `install.py --features openstack` fails with "No matching distribution found for gc3pieopenstack"

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#587]
The installation script apparently passes the wrong dependency name to
`pip install` when the "openstack" feature is requested::

    $ python install.py --overwrite -a openstack --yes

    ==========================
    GC3Pie installation script
    ==========================

    This script installs *latest stable version* of GC3Pie in '/home/ubuntu/gc3pie'.

    If you encounter any problem running this script, please contact
    the GC3Pie team by sending an email to gc3pie@googlegroups.com.

    Remember to attach the full output of the script, in order to help us
    to identify the problem.

    Installation info:

        Destination directory:    /home/ubuntu/gc3pie
        Overwrite existing dir:   yes
        Python executable:        /usr/bin/python
        Ask for confirmation:     no
        Install unreleased code:  no
        Install gc3apps:          yes
        Optional features:        ['openstack']
        Installer script version: 2.0.2

    Are you ready to continue? (Assuming a 'yes' reply because of `--yes` command-line option.)
    <GC3Pie install>     INFO: Deleting directory '/home/ubuntu/gc3pie' as requested ...
    Already using interpreter /usr/bin/python
    New python executable in /home/ubuntu/gc3pie/bin/python
    Installing setuptools..............................done.
    Installing pip.................................done.
    <GC3Pie install>     INFO: Created Python virtual environment in '/home/ubuntu/gc3pie'
    <GC3Pie install>     INFO: Trying to install or upgrade setuptools ...
    <GC3Pie install>     INFO: `easy_install` is available, using it to upgrade setuptools
    Searching for setuptools
    Reading http://pypi.python.org/simple/setuptools/
    Best match: setuptools 28.8.0
    Processing setuptools-28.8.0-py2.7.egg
    Removing setuptools 0.6c11 from easy-install.pth file
    Adding setuptools 28.8.0 to easy-install.pth file
    Installing easy_install script to /home/ubuntu/gc3pie/bin
    Installing easy_install-2.7 script to /home/ubuntu/gc3pie/bin

    Using /home/ubuntu/gc3pie/lib/python2.7/site-packages/setuptools-28.8.0-py2.7.egg
    Processing dependencies for setuptools
    Finished processing dependencies for setuptools
    <GC3Pie install>     INFO: Installing GC3Pie released code from PyPI ...
    <GC3Pie install>     INFO: Installing GC3Pie from PyPI package with '/home/ubuntu/gc3pie/bin/pip' ...
    Collecting gc3pieopenstack
      Could not find a version that satisfies the requirement gc3pieopenstack (from versions: )
    No matching distribution found for gc3pieopenstack
    Traceback (most recent call last):
      File "install.py", line 982, in <module>
        main()
      File "install.py", line 137, in main
        install_gc3pie_from_pypi(options.target, options.features)
      File "install.py", line 720, in install_gc3pie_from_pypi
        .format(features_for_pip=str.join(' ', features), **locals()))
      File "install.py", line 956, in run_in_virtualenv
        check_call(cmd, shell=True)
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '. /home/ubuntu/gc3pie/bin/activate; pip install 'gc3pieopenstack'' returned non-zero exit status 1

**Comment by riccardomurri** [comment]
This issue is already fixed in the development version, i.e., `python install.py --develop` runs correctly.
