### ISSUE TITLE
Traceback when running EasyBuild jobs

### ISSUE THREAD

**Issue by verdurin** [uzh/gc3pie#622]
I'm using `GC3Pie` to build modules with `EasyBuild` and I've just seen this traceback:
```
== GC3Pie job overview: 19 terminated, 19 ok, 1 running (total: 53)
== GC3Pie job overview: 20 terminated, 20 ok (total: 53)
== GC3Pie job overview: 20 terminated, 20 ok, 8 submitted (total: 53)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/main.py", line 475, in <module>
    main()
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/main.py", line 435, in main
    submit_jobs(ordered_ecs, eb_go.generate_cmd_line(), testing=testing)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/tools/parallelbuild.py", line 144, in submit_jobs
    return build_easyconfigs_in_parallel(command, ordered_ecs, prepare_first=prepare_first)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/tools/parallelbuild.py", line 114, in build_easyconfigs_in_parallel
    active_job_backend.complete()
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/tools/job/gc3pie.py", line 239, in complete
    self._engine.progress()
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 1305, in progress
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 416, in update_job_state
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 452, in __update_application
IndexError: string index out of range
```

**Comment by verdurin** [comment]
This is running version `2.4.2`.

**Comment by verdurin** [comment]
Similar error:
```
== 2017-05-26 00:33:21,217 batch.py:603 DEBUG Retrieving accounting information using command 'env SLURM_TIME_FORMAT=standard sacct --noheader --parsable --format jobid,exitcode,state,ncpus,elapsed,totalcpu,submit,start,end,maxrss,maxvmsize -j 3749518' ...
== 2017-05-26 00:33:21,336 transport.py:943 DEBUG Executed local command 'env SLURM_TIME_FORMAT=standard sacct --noheader --parsable --format jobid,exitcode,state,ncpus,elapsed,totalcpu,submit,start,end,maxrss,maxvmsize -j 3749518', got exit status: 0
== 2017-05-26 00:33:21,346 build_log.py:156 ERROR EasyBuild crashed with an error (at ?:651 in update_job_state): Error in querying Batch resource 'slurm': IndexError: string index out of range
== 2017-05-26 00:33:21,347 core.py:447 DEBUG Error getting status of application 'Application@252f750': IndexError: string index out of range
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 443, in __update_application
    state = lrms.update_job_state(app)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/__init__.py", line 166, in wrapper
    return fn(self, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/batch.py", line 605, in update_job_state
    return self.__do_acct(job, cmd, self._parse_acct_output)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/batch.py", line 530, in __do_acct
    jobstatus = parse(stdout)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/slurm.py", line 383, in _parse_acct_output
    vmem = SlurmLrms._parse_memspec(maxvmsize)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/slurm.py", line 425, in _parse_memspec
    unit = m[-1]
IndexError: string index out of range
```

**Comment by riccardomurri** [comment]
Can you please re-run the `sacct` command mentioned in the logs just before
the traceback and post the output here?

There should also be a similar SLURM command invocation before the first
traceback, can you please re-run it as well and post stdout+stderr?

**Comment by verdurin** [comment]
Here's the output of the first command:
```
# env SLURM_TIME_FORMAT=standard sacct --noheader --parsable --format jobid,exitcode,state,ncpus,elapsed,totalcpu,submit,start,end,maxrss,maxvmsize -j 3749518
3749518|0:0|COMPLETED|2|00:00:00|00:00:00|2017-05-26T00:32:50|2017-05-26T00:32:53|2017-05-26T00:32:53|||
3749518.batch|127:0|FAILED|2|00:00:00|00:00:00|2017-05-26T00:32:53|2017-05-26T00:32:53|2017-05-26T00:32:53|||
```

Here's the activity immediately preceding the traceback - is this what you mean?
```
== 2017-05-26 00:33:21,177 core.py:435 DEBUG About to update state of application: Application@252f750 (currently: SUBMITTED)
== 2017-05-26 00:33:21,177 __init__.py:169 DEBUG Checking auth: NoneAuth (always successful).
== 2017-05-26 00:33:21,178 transport.py:893 DEBUG Opening LocalTransport...
== 2017-05-26 00:33:21,178 batch.py:567 DEBUG Checking remote job status with 'squeue --noheader -o %i^%T^%r -j 3749518' ...
== 2017-05-26 00:33:21,216 transport.py:943 DEBUG Executed local command 'squeue --noheader -o %i^%T^%r -j 3749518', got exit status: 0
== 2017-05-26 00:33:21,217 __init__.py:1811 DEBUG Calling state-transition handler 'terminating' on Application@252f750 ...
```

That command fails now because the job isn't running.

**Comment by cmeesters** [comment]
Is there any news on this bug? We are experiencing this, too.

**Comment by riccardomurri** [comment]
Oh, sorry I forgot to update... This is fixed in GC3Pie "master", so you can just install the code from GitHub and it should run fine. For EasyBuild, you will need to merge https://github.com/easybuilders/easybuild-framework/pull/2373 into the framework code (or push @boegel to do it ;-))
