### ISSUE TITLE
Errors parsing `qacct` output on Univa Grid Engine

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#632]
Problem originally reported by @verdurin on the EasyBuild chat:

```
== 2017-12-19 11:27:29,802 build_log.py:158 ERROR EasyBuild crashed with an error (at ?:130 in _parse_asctime): Cannot parse '12/19/2017 11:26:55.707' as a SGE-format time stamp: ValueError: time data '12/19/2017 11:26:55.707' does not match format '%a %b %d %H:%M:%S %Y'
```

Indeed, `12/19/2017 11:26:55.707` does not match the `strptime()` format `%a %b %d %H:%M:%S %Y`.

**Comment by riccardomurri** [comment]
Digging into the sources for SoGE 8.1.9 (which is publicly available, whereas Univa sources aren't), we can see that the `*_time` fields in `qacct -j` output are produced at [lines 1437--1449](https://gitlab.com/loveshack/sge-release/blob/master/source/clients/qacct/qacct.c#L1437) of file `clients/qacct/qacct.c`, and they rely on function `sge_ctime32()`.  This function can be found at [`libs/uti/sge_time.c` lines 267--280](https://gitlab.com/loveshack/sge-release/blob/master/source/libs/uti/sge_time.c#L267), and we see it is just a wrapper for the libc standard function `ctime()`.  Now the [POSIX standard for `ctime()`](http://pubs.opengroup.org/onlinepubs/009695399/functions/ctime.html) states that:

> The ctime() function *[...]* shall be equivalent to:
>
>        asctime(localtime(clock))

So the string representation is controlled by `asctime()`, and the [POSIX standard for `asctime()`](http://pubs.opengroup.org/onlinepubs/009695399/functions/asctime.html) mandates that:

> The asctime() function shall convert *[...]* into a string in the form:
>
>        Sun Sep 16 01:03:52 1973\n\0

There is therefore no customization point upon which one can act to control `qacct`'s rendering of date/time, and GC3Pie's code is correctly parsing the output of SoGE 8.1.9 and the historical GridEngine sources.

**Comment by riccardomurri** [comment]
On the other hand, there are functions `sge_ctime()` and
`sge_ctimeXML()` (SoGE sources, `libs/uti/sge_time.c`) that use a
different date/time output format:

```c
const char *sge_ctime(time_t i, dstring *buffer)
{
   // ...
   sge_dstring_sprintf(buffer, "%02d/%02d/%04d %02d:%02d:%02d",
           tm->tm_mon + 1, tm->tm_mday, 1900 + tm->tm_year,
           tm->tm_hour, tm->tm_min, tm->tm_sec);
   // ...
}

/* TODO: should be replaced by sge_dstring_append_time() */
const char *sge_ctimeXML(time_t i, dstring *buffer)
{
   // ...
   sge_dstring_sprintf(buffer, "%04d-%02d-%02dT%02d:%02d:%02d",
           1900 + tm->tm_year, tm->tm_mon + 1, tm->tm_mday,
           tm->tm_hour, tm->tm_min, tm->tm_sec);
   // ...
}
```

So it looks like that trying alternate `strptime()` formats `%m/%d/%Y
%H:%M:%S` and `%Y-%m-%dT%H:%M:%S` should exhaust other possible output
formats.

**Comment by verdurin** [comment]
@riccardomurri - just tried this with the patch on top of `2.4.2` and saw this error, I'm afraid:
```
== resolving dependencies ...
== GC3Pie job overview: 5 submitted (total: 9)
Traceback (most recent call last):
  File "/apps/well/python/2.7.11/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/apps/well/python/2.7.11/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/gpfs2/well/rescomp/eb/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/main.py", line 504, in <module>
    main()
  File "/gpfs2/well/rescomp/eb/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/main.py", line 461, in main
    submit_jobs(ordered_ecs, eb_go.generate_cmd_line(), testing=testing)
  File "/well/rescomp/eb/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/tools/parallelbuild.py", line 144, in submit_jobs
    return build_easyconfigs_in_parallel(command, ordered_ecs, prepare_first=prepare_first)
  File "/well/rescomp/eb/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/tools/parallelbuild.py", line 114, in build_easyconfigs_in_parallel
    active_job_backend.complete()
  File "/well/rescomp/eb/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/tools/job/gc3pie.py", line 239, in complete
    self._engine.progress()
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 1305, in progress
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 416, in update_job_state
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 452, in __update_application
AttributeError: 'module' object has no attribute 'strptime'
```

**Comment by riccardomurri** [comment]
I think you need to apply both  d4cf858 and fc88353 -- I made a typo in the first one, which is corrected in the second.
