### ISSUE TITLE
'LocalTransport' object has no attribute 'remote_frontend'

### ISSUE THREAD

**Issue by oliviermattelaer** [uzh/gc3pie#638]
Hi,

I'm running gc3pie via the easybuild framework using the following configuration file

```
[resource/slurm]
enabled = yes
type = slurm

# use settings below when running GC3Pie on the cluster front-end node
frontend = localhost
transport = local
auth = none

max_walltime = 1 days
# max # jobs ~= max_cores / max_cores_per_job
max_cores_per_job = 24
max_cores = 24
max_memory_per_core = 2 GiB
architecture = x86_64

# to add non-std options or use SLURM tools located outside of
# the default PATH, use the following:
sbatch = /usr/bin/sbatch -D /scratch/softtmp
```

It succesfully submit jobs on the cluster but as soon as the first job completes the code crashes with the following error:

```
-bash-4.2$ eb /usr/easybuild/easyconfigs/a/ABINIT/ABINIT-8.2.2-intel-2016b.eb --configfiles=/opt/cecisw/arch/easybuild/2016b/config.cfg -r --job  --buildpath=. --debug
== temporary log file in case of crash /tmp/eb-4wUT6v/easybuild-HqUtKm.log
== resolving dependencies ...
== GC3Pie job overview: 3 submitted (total: 8)
== GC3Pie job overview: 3 running (total: 8)
== GC3Pie job overview: 3 running (total: 8)
== GC3Pie job overview: 3 running (total: 8)
== GC3Pie job overview: 3 running (total: 8)
== GC3Pie job overview: 3 running (total: 8)
== GC3Pie job overview: 3 running (total: 8)
== GC3Pie job overview: 3 running (total: 8)
== GC3Pie job overview: 3 running (total: 8)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/easybuild/main.py", line 504, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/easybuild/main.py", line 461, in main
    submit_jobs(ordered_ecs, eb_go.generate_cmd_line(), testing=testing)
  File "/usr/lib/python2.7/site-packages/easybuild/tools/parallelbuild.py", line 144, in submit_jobs
    return build_easyconfigs_in_parallel(command, ordered_ecs, prepare_first=prepare_first)
  File "/usr/lib/python2.7/site-packages/easybuild/tools/parallelbuild.py", line 114, in build_easyconfigs_in_parallel
    active_job_backend.complete()
  File "/usr/lib/python2.7/site-packages/easybuild/tools/job/gc3pie.py", line 248, in complete
    self._engine.progress()
  File "/usr/local/Software/gc3pie/lib64/python2.7/site-packages/gc3libs/core.py", line 1594, in progress
    changed_only=self.retrieve_changed_only)
  File "/usr/local/Software/gc3pie/lib64/python2.7/site-packages/gc3libs/core.py", line 592, in fetch_output
    app, download_dir, overwrite, changed_only, **extra_args)
  File "/usr/local/Software/gc3pie/lib64/python2.7/site-packages/gc3libs/core.py", line 659, in __fetch_output_application
    raise ex
AttributeError: 'LocalTransport' object has no attribute 'remote_frontend'
```

Do you know what can cause this?

Thanks in advance,

Olivier

**Comment by oliviermattelaer** [comment]
Here is the information from the python library:

```
>>> import gc3libs
>>> gc3libs.__version__
'2.4.2 version (SVN $Revision: 4328 $)'
```
I install it last week so it should be in principle the latest official release.

Thanks,

Olivier

**Comment by riccardomurri** [comment]
This is the commit that fixes it: https://github.com/uzh/gc3pie/commit/cef7723f963da0dced8a0cf14a838fcbb0b96c83#diff-7a4c23aba9fe205a7865f974f34858cc

I'm afraid that 2.4.2 is quite outdated by now... I know I should make a new release... :-(

If you cannot apply the patch above, you can just upgrade to GC3Pie's "master" branch, that should be fine provided you're running a recent version of EasyBuild, i.e., one that includes this code: https://github.com/easybuilders/easybuild-framework/commit/01548febdea86bbc0c76263fd88ad09f6acb4c5a#diff-30c0c724e8b33847f917f22eca0af7a0
